name: Deploy.yml compliance checks

on:
  push:
    branches: [ "main" ]
    paths:
    - .github/workflows/deploy.yml
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  compliance-checks:
    uses: RohitDemo/compliance-rules/.github/workflows/compliance-checks.yml@main
